- api/vulkan/resources.md
Added links to Overv's planned vulkan tutorial, my repository (that'll host examples upon Vulkan launch) and the PowerVR webinars
> First tutorial and repository links, PowerVR webinars

- api/opencl/resources.md
> Add NOpenCL to binding list

- api/vulkan/resources.md
Added link to the RenderDoc graphics debugger
> Link to RenderDoc

- api/opencl/bluebox.md
Added OpenCL C++ compiler and standard library reference implementations
> Added OpenCL C++ github links

- api/opencl/resources.md
> Added up to date ruby binding to the list.

- api/vulkan/faq.md
Per our email thread in the WG.
> Updated UE4 question

- api/vulkan/resources.md
Go-lang Vulkan bindings.
https://github.com/vulkan-go/vulkan
> Add link to vulkan-go.

- api/spir/resources.md
Related to KhronosGroup/SPIRV-Tools#359.
> Document SPIRV-Tools extras & link to vim-spirv

- api/opencl/resources.md
A couple of miscellaneous updates to the list of OpenCL resources.
> Update OpenCL resources

- api/vulkan/resources.md
Added the NXP GTEC C++11 cross-platform demo framework including lots of samples for Vulkan, OpenGL ES, OpenVX, OpenCL, OpenVG and OpenCV.
> Added C++ DemoFramework link.

- api/vulkan/resources.md
Added vkmark to list of resources.
> Add vkmark to resources.md

- api/vulkan/resources.md
I added a new "libraries" category since I wasn't sure my header library fit into any of the other categories...
> Added Vulkan synchronization resources

- api/sycl/bluebox.md
- api/sycl/resources.md
To merge after December 6, 2017 6AM PST
> SYCL 1.2.1 final specification

- api/opencl/resources.md
- Added @CNugteren's CLBlast library
- Updated the dead link of OpenCL cookbook
> Added CLBlast & updated dead link

- api/opencl/resources.md
1)  Framework for Heterogeneous Medical Image Computing and Visualization. https://github.com/smistad/FAST/
2) The optimized OpenCL implementation of Gradient Vector Flow (GVF).
https://github.com/smistad/OpenCL-GVF
> OpenCL Resources

- api/opencl/resources.md
Hi!
We can add the new resource for OpenCL: OpenCL for Visual Studio Code
https://marketplace.visualstudio.com/items?itemName=galarius.vscode-opencl
> OpenCL for Visual Studio Code

- api/vulkan/resources.md
>  Add Vulkan Community Discord Server

- api/sycl/bluebox.md
The new specification is available!
> Update Khronos SYCL 1.2.1 specification to revision 5

- api/openxr/resources.md
This API is called OpenXR, not OpenCL :wink:
> Fix unfortunate copy paste (CL -> XR)

- api/vulkan/resources.md
Added some items that I saw missing from the Vulkan resources page
> Addition of some more Vulkan resources

- api/opencl/bluebox.md
There is now a single master branch for all 2.x versions.
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
> Fix OpenCL conformance tests branches

- api/vulkan/resources.md
This PR adds an entry Intel(R) GPA to `resources.md`.
> Update tools entry

- api/sycl/README.md
- api/sycl/bluebox.md
- api/sycl/resources.md
To be merged for SYCLcon once https://github.com/KhronosGroup/SYCL-Registry/pull/11 has been merged.
> SYCL 1.2.1 specification revision 7

- api/sycl/resources.md
Add more resources.
Move content from over-bloated main page to resource page.
Fix bugs.
> [WIP] SYCL summer cleaning

- api/vulkan/resources.md
> Add liblava

- api/opencl/community-resources.md
Hello! I would like to add [CLtracer](https://www.cltracer.com/) to the Resources page. Thank you in advance.
> Add CLtracer to the Resources page

- api/opencl/community-resources.md
> Suggesting to add CLIJ to the list of libraries

- api/sycl/resources.md
Add the SYCL for Safety Practitioners Codeplay Series to the Tutorial Section.
> Add Codeplay Tutorial

- api/opencl/assets/CXX_for_OpenCL.html
This html is built from v1.0 rev2 tag:
https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/cxxforopencl-v1.0-r2
> Uploaded C++ for OpenCL html
